---
# Per environment values which override defaults in hmpps-sg-validation-test2/values.yaml

generic-service:
  ingress:
    host: sg-validation-test2.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://sg-validation-test2.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: james-dev
